### ISSUE TITLE
error while retrieving fulfillment options in checkout

### ISSUE THREAD

**Issue by delagroove** [reactioncommerce/example-storefront#567]
Type: breaking

**Describe the bug**
No fulfillment methods will appear after filling out your address on checkout step 1

**console**
`ERROR Reaction: shipping.0.shipmentQuotes.0.method.fulfillmentTypes is not allowed by the schema (errorId=ck037557k00016cp47wgr9q0j)
   path: [
     "updateFulfillmentOptionsForGroup"
   ]
   stack: ReactionError: shipping.0.shipmentQuotes.0.method.fulfillmentTypes is not allowed by the schema
       at Function.SimpleSchema.defineValidationErrorTransform.error [as validationErrorTransform] (imports/collections/schemas/schemaErrors.js:8:20)
       at /opt/reaction/src/node_modules/simpl-schema/dist/SimpleSchema.js:757:30
       at Array.forEach (<anonymous>)
       at SimpleSchema.validate (/opt/reaction/src/node_modules/simpl-schema/dist/SimpleSchema.js:730:15)
       at Promise.asyncApply (imports/plugins/core/cart/server/no-meteor/mutations/transformAndValidateCart.js:49:3)
       at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
    => awaited here:
       at Function.Promise.await (/home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
       at Promise.asyncApply (imports/plugins/core/cart/server/no-meteor/mutations/saveCart.js:14:3)
       at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
    => awaited here:
       at Function.Promise.await (/home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
       at Promise.asyncApply (imports/plugins/core/shipping/server/no-meteor/mutations/updateFulfillmentOptionsForGroup.js:94:20)
       at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
    => awaited here:
       at Function.Promise.await (/home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
       at Promise.asyncApply (imports/plugins/core/shipping/server/no-meteor/resolvers/Mutation/updateFulfillmentOptionsForGroup.js:24:9)
       at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40`

**To Reproduce**
1. in the admin area, make sure there's fulfillment methods activated. (i have 2)

2. start the checkout process with any products in cart. fill out address in step 1 and save

**Expected behavior**
Step 2 should show options for shipping and a way to go to step 3.

**Screenshots**
Fulfilment methods active
<img width="925" alt="Screen Shot 2019-09-02 at 10 15 58 PM" src="https://user-images.githubusercontent.com/57527/64139649-a0ba5080-cdcf-11e9-9eee-eb831c7785be.png">

error shown (address from step 1 deleted intentionally)
<img width="925" alt="no-fulfillment" src="https://user-images.githubusercontent.com/57527/64139568-5afd8800-cdcf-11e9-8382-2b261d7f40a0.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Mac
 - Browser [e.g. chrome, safari]: Any

**Smartphone (please complete the following information):**

**Additional context**
reaction -v

Node: 8.11.4
NPM: 5.6.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.2.0

**Comment by delagroove** [comment]
possible solution
https://github.com/reactioncommerce/reaction/issues/5513

**Comment by aldeed** [comment]
Upgrading to 2.2.1 should fix this.
