### ISSUE TITLE
Cannot read property 'currency' of null

### ISSUE THREAD

**Issue by paales** [reactioncommerce/example-storefront#617]
Type: breaking

**Describe the bug**
Trying out Reaction Commerce, but running into issues pretty quickly.

```
Cannot read property 'currency' of null
TypeError: Cannot read property 'currency' of null
    at /usr/local/src/app/node_modules/@reactioncommerce/components/CatalogGridItem/v1/utils/priceByCurrencyCode.js:17:18
    at Array.find (<anonymous>)
    at priceByCurrencyCode (/usr/local/src/app/node_modules/@reactioncommerce/components/CatalogGridItem/v1/utils/priceByCurrencyCode.js:16:26)
    at CatalogGridItem.renderProductInfo (/usr/local/src/app/node_modules/@reactioncommerce/components/CatalogGridItem/v1/CatalogGridItem.js:159:58)
    at CatalogGridItem.render (/usr/local/src/app/node_modules/@reactioncommerce/components/CatalogGridItem/v1/CatalogGridItem.js:187:97)
    at processChild (/usr/local/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2959:18)
    at resolve (/usr/local/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (/usr/local/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (/usr/local/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToStaticMarkup (/usr/local/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3661:27)
    at process (/usr/local/src/app/node_modules/react-apollo/react-apollo.umd.js:118:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**To Reproduce**
1. Created a new product in the operator panel (don't think it has anything to do with it).
2. http://localhost:4000/
3. Getting error.

**Expected behavior**
Working page

**Comment by poioit** [comment]
Did you fix this issue?
I run docker on google cloud and have a similar issue.

TypeError: Cannot read property '_id' of null
web_1  |     at _callee2$ (/usr/local/src/app/build/app/server/static/development/pages/_app.js:6260:22)
web_1  |     at tryCatch (/usr/local/src/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
web_1  |     at Generator.invoke [as _invoke] (/usr/local/src/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
web_1  |     at Generator.prototype.(anonymous function) [as next] (/usr/local/src/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
web_1  |     at asyncGeneratorStep (/usr/local/src/app/build/app/server/static/development/pages/_app.js:6163:103)
web_1  |     at _next (/usr/local/src/app/build/app/server/static/development/pages/_app.js:6165:194)

_app.js:6260 is the code for primaryshop is null

**To Reproduce**
Steps to reproduce the behavior:

1. http://server-ip:4000/
2. Getting error.

**Expected behavior**
Working page

**Comment by paales** [comment]
Nope, I gave up 😭

**Comment by HarisSpahijaPon** [comment]
@poioit Could you see if you have any traffic between your frontend and backend when a query is done? Google cloud should have an option to display logs. Also adding a repo with the reproduction of this bug will help solve this issue.
