### ISSUE TITLE
Errors in 3.0

### ISSUE THREAD

**Issue by griggheo** [reactioncommerce/example-storefront#620]
Getting these errors when hitting https://storefront.v3.reactioncommerce.io:

```
Server started ! ✓
      http://localhost:4000
      Press CTRL-C to stop
[GraphQL error]: Message: Field "tag" argument "shopId" of type "ID!" is required, but it was not provided., Location: [{"line":2,"column":3}], Path: undefined
[GraphQL error]: Message: Variable "$slugOrId" of type "String" used in position expecting type "String!"., Location: [{"line":1,"column":16},{"line":2,"column":17}], Path: undefined
Unable to access the GraphQL API. Is it running and accessible at http://v3-reaction-core/graphql-beta from the Storefront UI server?
{ Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/usr/local/src/app/node_modules/apollo-client/bundle.umd.js:99:32)
    at /usr/local/src/app/node_modules/apollo-client/bundle.umd.js:978:45
    at /usr/local/src/app/node_modules/apollo-client/bundle.umd.js:1345:21
    at Array.forEach (<anonymous>)
    at /usr/local/src/app/node_modules/apollo-client/bundle.umd.js:1344:22
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/usr/local/src/app/node_modules/apollo-client/bundle.umd.js:1339:26)
    at /usr/local/src/app/node_modules/apollo-client/bundle.umd.js:928:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
  graphQLErrors: [],
  networkError:
   { ServerError: Response not successful: Received status code 400
       at Object.exports.throwServerError (/usr/local/src/app/node_modules/apollo-link-http-common/lib/index.js:23:17)
       at /usr/local/src/app/node_modules/apollo-link-http-common/lib/index.js:48:21
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'ServerError',
     response:
      Body {
        url: 'http://v3-reaction-core/graphql-beta',
        status: 400,
        statusText: 'Bad Request',
        headers: [Headers],
        ok: false,
        body: [PassThrough],
        bodyUsed: true,
        size: 0,
        timeout: 0,
        _raw: [Array],
        _abort: false,
        _bytes: 412 },
     statusCode: 400,
     result: { errors: [Array] } },
  message:
   'Network error: Response not successful: Received status code 400',
  extraInfo: undefined }
[GraphQL error]: Message: Field "tag" argument "shopId" of type "ID!" is required, but it was not provided., Location: [{"line":2,"column":3}], Path: undefined
[GraphQL error]: Message: Variable "$slugOrId" of type "String" used in position expecting type "String!"., Location: [{"line":1,"column":16},{"line":2,"column":17}], Path: undefined
Unable to access the GraphQL API. Is it running and accessible at http://v3-reaction-core/graphql-beta from the Storefront UI server?
{ Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/usr/local/src/app/node_modules/apollo-client/bundle.umd.js:99:32)
    at /usr/local/src/app/node_modules/apollo-client/bundle.umd.js:978:45
    at /usr/local/src/app/node_modules/apollo-client/bundle.umd.js:1345:21
    at Array.forEach (<anonymous>)
    at /usr/local/src/app/node_modules/apollo-client/bundle.umd.js:1344:22
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/usr/local/src/app/node_modules/apollo-client/bundle.umd.js:1339:26)
    at /usr/local/src/app/node_modules/apollo-client/bundle.umd.js:928:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
  graphQLErrors: [],
  networkError:
   { ServerError: Response not successful: Received status code 400
       at Object.exports.throwServerError (/usr/local/src/app/node_modules/apollo-link-http-common/lib/index.js:23:17)
       at /usr/local/src/app/node_modules/apollo-link-http-common/lib/index.js:48:21
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'ServerError',
     response:
      Body {
        url: 'http://v3-reaction-core/graphql-beta',
        status: 400,
        statusText: 'Bad Request',
        headers: [Headers],
        ok: false,
        body: [PassThrough],
        bodyUsed: true,
        size: 0,
        timeout: 0,
        _raw: [Array],
        _abort: false,
        _bytes: 412 },
     statusCode: 400,
     result: { errors: [Array] } },
  message:
   'Network error: Response not successful: Received status code 400',
  extraInfo: undefined }
```

**Comment by aldeed** [comment]
@griggheo Latest 3.0 image should resolve this error: https://hub.docker.com/layers/reactioncommerce/example-storefront/release-v3.0.0/images/sha256-9ec9df13edb4f6f6b1e3d9342c3ae84a1c651db216dd581065a4fab1061aeac4

**Comment by griggheo** [comment]
Bingo!

https://storefront.v3.reactioncommerce.io/ works now! 

/cc @spencern
